# Generated by Django 4.1.3 on 2022-11-25 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolistitem',
            name='user',
            field=models.CharField(default='demotest@gmail.com', max_length=100),
            preserve_default=False,
        ),
    ]
