# Generated by Django 4.1.3 on 2022-12-07 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todoapp", "0004_todolistitem_shifts"),
    ]

    operations = [
        migrations.AddField(
            model_name="todolistitem",
            name="Ac_type",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="todolistitem",
            name="passengers",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
